// app/layout.tsx or app/layout.js
import { Fredoka, Noto_Sans_TC } from "next/font/google";
import "./globals.css";

const fredoka = Fredoka({
  subsets: ["latin"],          // for English/Latin text
  variable: "--font-fredoka",
});

const notoSansTC = Noto_Sans_TC({
  // Noto Sans TC is designed for Traditional Chinese. [web:21][web:12]
  weight: ["400"],             // add more weights if you need them
  variable: "--font-noto-sans-tc",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${notoSansTC.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
